export const langText = {
  Hinglish: {
    home: "Home",
    feature: "Feature",
    pricing: "Pricing",
    about: "About",
    contact: "Contact Us",
    dashboard: "Dashboard",
    login: "Login",
    register: "Register",
    product: "Product",
    company: "Company",
    support: "Support",
    help: "Help Centre",
    terms: "Terms and Conditions",
    policy: "Policy",
    privacy: "Privacy Policy",
    gst: "GST Policy",
    startFree: "Start Free Now To Grow Your Business",
    click: "Click",
    features: "Features",
    pricingPage: "Pricing",
    aboutUs: "About Us",
    contactPage: "Contact",
    powerfulFeatures: "Powerful Features for Modern Businesses",
    featuresDesc: "Everything you need to manage billing, inventory, and business growth from one smart dashboard.",
    servicesHeading: "Everything your billing should already do",
    thankYouTitle: "Thank You",
    thankYouMsg: "We have received your message. We will contact you shortly.",
    backToContact: "Back to Contact",
    newInvoice: "New Invoice",
    ...{},
  },
  Hindi: {
    home: "होम",
    feature: "फ़ीचर",
    pricing: "मूल्य निर्धारण",
    about: "हमारे बारे में",
    contact: "संपर्क करें",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    register: "रजिस्टर",
    product: "उत्पाद",
    company: "कंपनी",
    support: "सहायता",
    help: "सहायता केंद्र",
    terms: "नियम और शर्तें",
    policy: "नीति",
    privacy: "गोपनीयता नीति",
    gst: "जीएसटी नीति",
    startFree: "अभी मुफ्त में शुरू करें और अपने व्यवसाय को बढ़ाएं",
    click: "यहाँ क्लिक करें",
    features: "विशेषताएँ",
    pricingPage: "मूल्य निर्धारण",
    aboutUs: "हमारे बारे में",
    contactPage: "संपर्क करें",
    powerfulFeatures: "आधुनिक व्यवसायों के लिए शक्तिशाली विशेषताएँ",
    featuresDesc: "एक स्मार्ट डैशबोर्ड से बिलिंग, इन्वेंट्री और व्यापार वृद्धि प्रबंधित करने के लिए सब कुछ।",
    servicesHeading: "आपकी बिलिंग को ये सब पहले से करना चाहिए",
    thankYouTitle: "धन्यवाद",
    thankYouMsg: "हमें आपका संदेश मिल गया है। हम आपसे शीघ्र संपर्क करेंगे।",
    backToContact: "संपर्क पर वापस जाएं",
    newInvoice: "नया इनवॉइस",
    ...{},
  },
  English: {
    home: "Home",
    feature: "Feature",
    pricing: "Pricing",
    about: "About",
    contact: "Contact Us",
    dashboard: "Dashboard",
    login: "Login",
    register: "Register",
    product: "Product",
    company: "Company",
    support: "Support",
    help: "Help Centre",
    terms: "Terms and Conditions",
    policy: "Policy",
    privacy: "Privacy Policy",
    gst: "GST Policy",
    startFree: "Start Free Now To Grow Your Business",
    click: "Click",
    features: "Features",
    pricingPage: "Pricing",
    aboutUs: "About Us",
    contactPage: "Contact",
    powerfulFeatures: "Powerful Features for Modern Businesses",
    featuresDesc: "Everything you need to manage billing, inventory, and business growth from one smart dashboard.",
    servicesHeading: "Everything your billing should already do",
    thankYouTitle: "Thank You",
    thankYouMsg: "We have received your message. We will contact you shortly.",
    backToContact: "Back to Contact",
    newInvoice: "New Invoice",
    ...{},
  },
} as const;
